version: '2'

networks:
  cluster:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.20.0.0/24
        gateway: 172.20.0.254

services:
  dns1:
    build: '.'
    image: wrouesnel/powerdns-cluster
    expose:
    - 8081/tcp
    - 53/tcp
    - 53/udp
    networks:
      cluster:
        ipv4_address: 172.20.0.1
  dns2:
    build: '.'
    image: wrouesnel/powerdns-cluster
    expose:
    - 8081/tcp
    - 53/tcp
    - 53/udp
    networks:
      cluster:
        ipv4_address: 172.20.0.2
  dns3:
    build: '.'
    image: wrouesnel/powerdns-cluster
    expose:
    - 8081/tcp
    - 53/tcp
    - 53/udp
    networks:
      cluster:
        ipv4_address: 172.20.0.3
  dns4:
    build: '.'
    image: wrouesnel/powerdns-cluster
    expose:
    - 8081/tcp
    - 53/tcp
    - 53/udp
    networks:
      cluster:
        ipv4_address: 172.20.0.4
  dns5:
    build: '.'
    image: wrouesnel/powerdns-cluster
    expose:
    - 8081/tcp
    - 53/tcp
    - 53/udp
    networks:
      cluster:
        ipv4_address: 172.20.0.5
